name: Docker-Auth

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      

      - name: Build Docker image
        run: docker build -t your-username/my-image:latest .    

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-ci-image:v1.1.1
      
      
        

      - name: Build the app container
        run: docker build -t auth-image ./

      

 