name: Docker-Auth

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Build the app container
        run: docker build -t auth-image ./

      - name: Scan the Docker image with Anchore
        uses: anchore/scan-action@v2
        with:
          image: sauth-image:latest

 